#已k: v 关键字冒号空格值。组成了一组键值对
#若一个键下面有多个属性，子属性直接要缩进保持一致。至于缩进的量没有限制

#配置日志相关,配置日志级别，包含并且大于此级别的都会打印
#server:
 # port: 8082
#     address: jdbc://
#spring:
#  datasource:
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

#大小写敏感。
# "" ： 字符串会识别特殊字符并执行/不会转义。  '': 字符串中特殊字符会进行转义处理
person:
  name: '张三 \n 李思'
  age: 22
  car:
    name: 兰博基尼
    color: 红色
  map: {k1: 15,k2: vivo}
#    k1: v1
#    k2: v2
  list:
    - lucy
    - lily
    - tom
  birthday: 2020/01/22
  test: 111

logging:
  level:
    com.weichuang.fellows44_springboot: debug


#spring:
 # profiles:
 #   active: dev



#yml 文件支持多文档块的写法
#激活方式spring.profiles.active=prod
---
#server:
#  port: 8085
#spring:
#  profiles: dev

---
#server:
#  port: 8086
#spring:
#  profiles: prod

###################################
# 配置数据源
##################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: weichuang2021
    username: root
    url: jdbc:mysql://81.70.223.139:3307/fellows44_springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
#################################
# 配置Redis连接
##################################
  redis:
    host: 81.70.223.139

